/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Resource = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
});
export const StudySession = IDL.Record({
  'subject' : IDL.Text,
  'date' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Goal = IDL.Record({
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'targetDate' : IDL.Text,
  'category' : IDL.Text,
  'priority' : Priority,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ProgressStats = IDL.Record({
  'totalStudyMinutes' : IDL.Nat,
  'totalGoals' : IDL.Nat,
  'completedGoals' : IDL.Nat,
  'currentStreak' : IDL.Nat,
  'distinctStudyDays' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addResource' : IDL.Func([Resource], [], []),
  'addStudySession' : IDL.Func([StudySession], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGoal' : IDL.Func([Goal], [], []),
  'deleteGoal' : IDL.Func([IDL.Text], [], []),
  'deleteResource' : IDL.Func([IDL.Text], [], []),
  'deleteStudySession' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getProgressStats' : IDL.Func([], [ProgressStats], ['query']),
  'getResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markGoalComplete' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateGoal' : IDL.Func([IDL.Text, Goal], [], []),
  'updateResource' : IDL.Func([IDL.Text, Resource], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Resource = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
  });
  const StudySession = IDL.Record({
    'subject' : IDL.Text,
    'date' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Goal = IDL.Record({
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'targetDate' : IDL.Text,
    'category' : IDL.Text,
    'priority' : Priority,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ProgressStats = IDL.Record({
    'totalStudyMinutes' : IDL.Nat,
    'totalGoals' : IDL.Nat,
    'completedGoals' : IDL.Nat,
    'currentStreak' : IDL.Nat,
    'distinctStudyDays' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addResource' : IDL.Func([Resource], [], []),
    'addStudySession' : IDL.Func([StudySession], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGoal' : IDL.Func([Goal], [], []),
    'deleteGoal' : IDL.Func([IDL.Text], [], []),
    'deleteResource' : IDL.Func([IDL.Text], [], []),
    'deleteStudySession' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getProgressStats' : IDL.Func([], [ProgressStats], ['query']),
    'getResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markGoalComplete' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateGoal' : IDL.Func([IDL.Text, Goal], [], []),
    'updateResource' : IDL.Func([IDL.Text, Resource], [], []),
  });
};

export const init = ({ IDL }) => { return []; };