/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Goal {
  'title' : string,
  'completed' : boolean,
  'description' : string,
  'targetDate' : string,
  'category' : string,
  'priority' : Priority,
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface ProgressStats {
  'totalStudyMinutes' : bigint,
  'totalGoals' : bigint,
  'completedGoals' : bigint,
  'currentStreak' : bigint,
  'distinctStudyDays' : bigint,
}
export interface Resource {
  'url' : string,
  'title' : string,
  'notes' : [] | [string],
  'category' : string,
}
export interface StudySession {
  'subject' : string,
  'date' : string,
  'durationMinutes' : bigint,
  'notes' : [] | [string],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addResource' : ActorMethod<[Resource], undefined>,
  'addStudySession' : ActorMethod<[StudySession], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGoal' : ActorMethod<[Goal], undefined>,
  'deleteGoal' : ActorMethod<[string], undefined>,
  'deleteResource' : ActorMethod<[string], undefined>,
  'deleteStudySession' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGoals' : ActorMethod<[], Array<Goal>>,
  'getProgressStats' : ActorMethod<[], ProgressStats>,
  'getResources' : ActorMethod<[], Array<Resource>>,
  'getStudySessions' : ActorMethod<[], Array<StudySession>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markGoalComplete' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateGoal' : ActorMethod<[string, Goal], undefined>,
  'updateResource' : ActorMethod<[string, Resource], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];